version: "3.8"

services:
  faulty-app:
    build:
      context: ./faulty-app
      dockerfile: Dockerfile
    container_name: faulty-app
    ports:
      - "3000:3000"
    volumes:
      - crash-data:/tmp
    command: ["node", "server.js"]
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3100:3100"
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana

  exporter:
    build:
      context: .
      dockerfile: Dockerfile.exporter
    container_name: exporter
    ports:
      - "8000:8000"
    volumes:
      - ./data/outputs:/app/data/outputs
    restart: always

volumes:
  grafana-storage:
  crash-data:
