services:
  faulty-app:
    build:
      context: ./faulty-app
      dockerfile: Dockerfile
    container_name: faulty-app
    ports:
      - "3100:3000"
    volumes:
      - ./data/outputs:/app/data/outputs
    command: ["node", "server.js"]
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3030:3000"
    restart: always
